### ISSUE TITLE
Fetch puppet-akamai-dns via https instead of SSH

### ISSUE THREAD

**Issue by gozer** [bhourigan/nubis-akamai-dns#1]
From nubis/Puppetfile:

```
mod 'bhourigan/puppet-akamai-dns',
    :git => 'git@github.com:bhourigan/puppet-akamai-dns.git'
```

This should be pulling from https://github.com/bhourigan/puppet-akamai-dns.git instead, as the CI system will not be able to clone from SSH as can be seen here:

http://ci.akamai.admin.us-east-1.plan-b-akamai-edns-slave.nubis.allizom.org/job/akamai-build/1/console

**Comment by bhourigan** [comment]
Fixed https://github.com/bhourigan/nubis-akamai-dns/commit/8c3738ad263a8e315babc90ab78002047ad9cd50
